Bump deps, remove Cargo.lock from gitignore
In a stale git worktree, I was getting errors like:

  error: failed to select a version for `arbitrary`.
      ... required by package `sherman v0.1.0 (/path/to/sherman)`
      ... which satisfies path dependency `sherman` (locked to 0.1.0) of package `sherman-fuzz v0.0.0 (/path/to/sherman/fuzz)`
  versions that meet the requirements `^1.4.2` are: 1.4.2

  all possible versions conflict with previously selected packages.

    previously selected package `arbitrary v1.2.0`
      ... which satisfies dependency `arbitrary = "^1"` (locked to 1.2.0) of package `libfuzzer-sys v0.4.5`
      ... which satisfies dependency `libfuzzer-sys = "^0.4"` (locked to 0.4.5) of package `sherman-fuzz v0.0.0 (/path/to/sherman/fuzz)`

which were because fuzz/Cargo.lock had `arbitrary` locked to v1.2.0 but
the main Cargo.toml/Cargo.lock had `arbitrary` at v1.4.2.

To fix this, let's both (a) update the deps in fuzz/ to match the main
crate, and (b) make both Cargo.lock files checked into git so that the
situation is easier to reason about.